### ISSUE TITLE
TODO formatting messes up

### ISSUE THREAD

**Issue by PsHyC0** [dmytrodubinin/Harmony-theme-for-Logseq#3]
Love the colors and formatting for the most part with the theme but for some reason when I do a task the text goes vertical and overwrites next line.

![image](https://user-images.githubusercontent.com/60897860/163435569-e3c3fcf1-c61b-4d0c-bcf2-b6882e79fabe.png)

**Comment by dmytrodubinin** [comment]
Your screenshot is not my theme. Below is an example display (other colors are visible), I used the theme from the marketplace.
![image](https://user-images.githubusercontent.com/8066458/163538481-934c6893-e108-4f42-8367-1dc7c792c1ce.png)

Please make sure you are using my theme
