### ISSUE TITLE
Code blocks line height 

### ISSUE THREAD

**Issue by Fastidious** [dmytrodubinin/Harmony-theme-for-Logseq#4]
Code blocks lines are a little too tight. Could the line height on code blocks be increased a little bit?

**Comment by dmytrodubinin** [comment]
![image](https://user-images.githubusercontent.com/8066458/164266850-e08358fc-b962-4b69-a218-1197435cb13e.png)
I don't see that code blocks are tight. Please provide an example as you would like (preferably with screenshots)
I removed the very large indents that were originally. Here are screenshots of the current state, are we talking about these indents to do a little more?

**Comment by Fastidious** [comment]
Code block lines, not in-between code blocks space. I am talking about code block line height.

<img width="1294" alt="Screenshot 2022-04-20 at 11 29 43" src="https://user-images.githubusercontent.com/8352292/164267468-7180e4c3-1c87-4808-acc1-641906f17578.png">

**Comment by dmytrodubinin** [comment]
Like this?
Old version:
![image](https://user-images.githubusercontent.com/8066458/164268514-781ba8d0-b258-4c9a-843f-cd45010ee7d0.png)
New version:
![image](https://user-images.githubusercontent.com/8066458/164268422-261b02f5-73a3-47dc-a0b7-8deb39b9f0c5.png)

**Comment by Fastidious** [comment]
Yes, that's better. It makes it more readable.

**Comment by dmytrodubinin** [comment]
Update theme via marketplace. If ok, close issue

**Comment by Fastidious** [comment]
Thanks!
