### ISSUE TITLE
Wired trailing block in a line with inline code block

### ISSUE THREAD

**Issue by Xuanwo** [dmytrodubinin/Harmony-theme-for-Logseq#5]
Hi, thanks for the great theme at first.

---

If a line contains an inline code block like the following:

```
`multipart_write() -> MultipartWriter`
```

We will get a wired trailing block at the end of this line:

![image](https://user-images.githubusercontent.com/5351546/166411377-9b7ffe1e-b6bf-4438-9a78-4d1b5d01b9e7.png)

Is this behavior by design? Based on my daily usage, I found it's eye-catching and not comfortable.

For example: https://note.xuanwo.io/#/page/rust%2Fstd%2Fpin

**Comment by dmytrodubinin** [comment]
Thanks for the feedback!
In white theme the design is correct:
![image](https://user-images.githubusercontent.com/8066458/166415096-93a1c0ff-f53b-49ba-ae02-1ce3639dfdd5.png)
Perhaps you have suggestions for design. I almost always use the dark theme, so the light theme might have some bugs.
The light theme retains its minimalism and affinity with the dark theme. Inline code blocks look acceptable to me

**Comment by Xuanwo** [comment]
After switching to the default theme, the trailing block still exists. Maybe it's a logseq-related problem.

I'm closing this issue now, thanks for the quick response!

**Comment by dmytrodubinin** [comment]
Thanks for using my theme. Good luck!
